version: 2.1
orbs:
  my-cicd-orb: my-company-name/my-cicd-orb@1.0.1

workflows:
  version: 2
  release_pipeline:
    jobs:
      - my-cicd-orb/my-task:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
